---
galaxy_info:
  author: Donald Duck
  description: Install and configure Nginx web server
  company: Andeby A/S

  license: GPL-3.0-or-later

  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - nginx
    - web
    - webserver

dependencies: []